image: node:6.9.4

pipelines:
  master:
    - step:
        caches:
          - node
        script:
          - npm install
          - npm run build
    - step:
        name: Deploy to prod
        deployment: prod
        script:
          - echo "Deploying to prod environment"
